platform :ios, '15.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# temporary version bump and target platform change
install! 'cocoapods', :disable_input_output_paths => true

target 'App' do
  # Google Maps SDK for iOS (native map rendering)
  pod 'GoogleMaps', '~> 8.4.0'

  # Google Places SDK for iOS (places autocomplete)
  pod 'GooglePlaces', '~> 8.5.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
